Emreraslan.Web/Areas/UserPanel/Controllers/DashboardController.cs
using Emreraslan.Services.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace Emreraslan.Web.Areas.UserPanel.Controllers
{
    [Area("UserPanel")]
    public class DashboardController : Controller
    {
        private readonly UserService _userService;

        public DashboardController(UserService userService)
        {
            _userService = userService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> LogOut()
        {
            await _userService.SignOutUser();

            return RedirectToAction("Index","Home", new {area = ""});
        }
    }
}

Emreraslan.Web/Areas/UserPanel/Controllers/OrderController.cs
using Emreraslan.Core.Entities;
using Emreraslan.Services.Abstract;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Emreraslan.Web.Areas.UserPanel.Controllers
{
    [Area("UserPanel")]
    public class OrderController : Controller
    {
        private readonly IHttpContextAccessor _contextAccessor;
        private readonly IOrderService _orderService;
        private readonly UserManager<User> _userManager;

        public OrderController(IOrderService orderService, UserManager<User> userManager,IHttpContextAccessor contextAccessor)
        {
            _orderService = orderService;
            _userManager = userManager;
            _contextAccessor = contextAccessor;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            if (_contextAccessor.HttpContext.User.Identity.IsAuthenticated)
            {
                var userName = _contextAccessor.HttpContext.User.Identity.Name;
                var user = await _userManager.FindByNameAsync(userName);
                if (user != null) 
                {
                    List<Order> orders = _orderService.GetAll(x => x.UserId == user.Id);
                    return View(orders);
                }
            }
            return NotFound();
        }

        public IActionResult DeleteOrder(int id)
        {
            var orderToDelete = _orderService.GetById(id);
            _orderService.Delete(orderToDelete);

            return RedirectToAction("Index");
        }
    }
}

Emreraslan.Web/Areas/VendorPanel/Controllers/ProfileController.cs
using Emreraslan.Core.Entities;
using Emreraslan.Services.Abstract;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Emreraslan.Web.Areas.VendorPanel.Controllers
{
    [Area("VendorPanel")]
    public class ProfileController : Controller
    {
        private readonly IHttpContextAccessor _contextAccessor;
        private readonly UserManager<User> _userManager;
        private readonly IVendorService _vendorService;

        public ProfileController(IHttpContextAccessor contextAccessor, UserManager<User> userManager, IVendorService vendorService)
        {
            _contextAccessor = contextAccessor;
            _userManager = userManager;
            _vendorService = vendorService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            if (_contextAccessor.HttpContext.User.Identity.IsAuthenticated)
            {
                var name = _contextAccessor.HttpContext.User.Identity.Name;

                var user = await _userManager.FindByNameAsync(name);

                var vendor = _vendorService.Get(x => x.UserId == user.Id);

                if (vendor == null)
                {
                    return NotFound();
                }

                return View(vendor);
            }

            return NotFound();
        }
    }
}

Emreraslan.Web/Areas/VendorPanel/Controllers/SettingsController.cs
using Microsoft.AspNetCore.Mvc;

namespace Emreraslan.Web.Areas.VendorPanel.Controllers
{
    [Area("VendorPanel")]
    public class SettingsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Emreraslan.Web/Areas/VendorPanel/Views/Shared/_Layout.cshtml
@{
    ViewData["Title"] = "_Layout";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!--vendor-area-Area -->
<section id="vendor_area" class="ptb-100">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-3">
                <!-- Nav tabs -->
                <div class="dashboard_tab_button">
                    <ul role="tablist" class="nav flex-column dashboard-list">
                        <li>
                            <a asp-area="VendorPanel" asp-controller="Dashboard" asp-action="Index">
                                <i class="fas fa-tachometer-alt"></i> Dashboard
                            </a>
                        </li>
                        <li>
                            <a asp-area="VendorPanel" asp-controller="Product" asp-action="Index">
                                <i class="fas fa-shopping-cart"></i>Product
                            </a>
                        </li>
                        <li>
                            <a asp-area="VendorPanel" asp-controller="Order" asp-action="Index">
                                <i class="fas fa-shopping-bag"></i>Order
                            </a>
                        </li>
                        <li>
                            <a asp-area="VendorPanel" asp-controller="Profile" asp-action="Index">
                                <i class="far fa-id-badge"></i>Profile
                            </a>
                        </li>
                        <li>
                            <a asp-area="VendorPanel" asp-controller="AddProduct" asp-action="Index">
                            <i class="fas fa-cart-plus"></i>Add PRoduct</a>
                        </li>
                        <li>
                            <a asp-area="VendorPanel" asp-controller="Settings" asp-action="Index">
                                <i class="fas fa-user-cog"></i>Setting
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-12 col-md-12 col-lg-9">
                <!-- Tab panes -->
                <div class="tab-content dashboard_content">
                    
                    @RenderBody()

                </div>
            </div>
        </div>
    </div>
</section>

@RenderSection("Scriptss",false)