Emreraslan.Web/Areas/UserPanel/Controllers/AddressController.cs
using Emreraslan.Core.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Emreraslan.Web.Areas.UserPanel.Controllers
{
    [Area("UserPanel")]
    public class AddressController : Controller
    {
        private readonly IHttpContextAccessor _contextAccessor;
        private readonly UserManager<User> _userManager;

        public AddressController(IHttpContextAccessor contextAccessor, UserManager<User> userManager)
        {
            _contextAccessor = contextAccessor;
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            if (_contextAccessor.HttpContext.User.Identity.IsAuthenticated)
            {
                var name = _contextAccessor.HttpContext.User.Identity.Name;

                var user = await _userManager.FindByNameAsync(name);

                return View(user);
            }

            return NotFound();
        }
    }
}

Emreraslan.Web/Areas/UserPanel/Controllers/BeVendorController.cs
using Emreraslan.Core.Entities;
using Emreraslan.Services.Abstract;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Emreraslan.Web.Areas.UserPanel.Controllers
{
    [Area("UserPanel")]
    public class BeVendorController : Controller
    {
        private readonly IVendorService _vendorService;
        private readonly IHttpContextAccessor _contextAccessor;
        private readonly UserManager<User> _userManager;
        private readonly ICategoryService _categoryService;
        public BeVendorController(IVendorService vendorService, UserManager<User> userManager,IHttpContextAccessor contextAccessor,ICategoryService categoryService)
        {
            _vendorService = vendorService;
            _contextAccessor = contextAccessor;
            _userManager = userManager;
            _categoryService = categoryService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var categories = _categoryService.GetAll();

            return View(categories);
        }

        [HttpPost]
        public async Task<JsonResult> Index(Vendor vendor)
        {
            if (_contextAccessor.HttpContext.User.Identity.IsAuthenticated)
            {
                string name = _contextAccessor.HttpContext.User.Identity.Name;

                var user = await _userManager.FindByNameAsync(name);

                if (user == null)
                {
                    return Json(new { isOk = false, message = "Kullanıcı bulunamadı." });
                }

                vendor.UserId = user.Id;

                int result = await Task.FromResult(_vendorService.Insert(vendor));

                if (result == 1)
                    return Json(new { isOk = true, message = "Kayıt başarılı." });
                else
                    return Json(new { isOk = false, message = "Kayıt başarısız!!!" });
            }

            return Json(new { isOk = false, message = "Kayıt başarısız!!!" });
        }
    }

    /*
            int result = await Task.FromResult(_vendorService.Insert(vendor));
            if (result == 1)
                return Json(new { isOk = true, message = "Kayıt başarılı." });
            else
                return Json(new { isOk = false, message = "Kayıt başarısız!!!" });
     */
}

Emreraslan.Web/Areas/UserPanel/Controllers/DashboardController.cs
using Emreraslan.Services.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace Emreraslan.Web.Areas.UserPanel.Controllers
{
    [Area("UserPanel")]
    public class DashboardController : Controller
    {
        private readonly UserService _userService;

        public DashboardController(UserService userService)
        {
            _userService = userService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> LogOut()
        {
            await _userService.SignOutUser();

            return RedirectToAction("Index","Home", new {area = ""});
        }
    }
}

Emreraslan.Web/Areas/UserPanel/Controllers/OrderController.cs
using Emreraslan.Core.Entities;
using Emreraslan.Services.Abstract;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Emreraslan.Web.Areas.UserPanel.Controllers
{
    [Area("UserPanel")]
    public class OrderController : Controller
    {
        private readonly IHttpContextAccessor _contextAccessor;
        private readonly IOrderService _orderService;
        private readonly UserManager<User> _userManager;

        public OrderController(IOrderService orderService, UserManager<User> userManager,IHttpContextAccessor contextAccessor)
        {
            _orderService = orderService;
            _userManager = userManager;
            _contextAccessor = contextAccessor;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            if (_contextAccessor.HttpContext.User.Identity.IsAuthenticated)
            {
                var userName = _contextAccessor.HttpContext.User.Identity.Name;
                var user = await _userManager.FindByNameAsync(userName);
                if (user != null) 
                {
                    List<Order> orders = _orderService.GetAll(x => x.UserId == user.Id);
                    return View(orders);
                }
            }
            return NotFound();
        }

        public IActionResult DeleteOrder(int id)
        {
            var orderToDelete = _orderService.GetById(id);
            _orderService.Delete(orderToDelete);

            return RedirectToAction("Index");
        }
    }
}

Emreraslan.Web/Areas/UserPanel/Views/Shared/_Layout.cshtml
@{
    ViewData["Title"] = "_Layout";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- My-account-area-Area -->
<section id="my-account_area" class="ptb-100">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-3">
                <!-- Nav tabs -->
                <div class="dashboard_tab_button">
                    <ul role="tablist" class="nav flex-column dashboard-list">   
                        <li>
                            <a asp-area="UserPanel" asp-controller="Dashboard" asp-action="Index">
                                <i class="fas fa-cart-arrow-down"></i>Dashboard
                            </a>
                        </li>
                        <li>
                            <a asp-area="UserPanel" asp-controller="Order" asp-action="Index">
                                <i class="fas fa-cart-arrow-down"></i>Orders
                            </a>
                        </li>                        
                        <li>
                            <a asp-area="UserPanel" asp-controller="Address" asp-action="Index">
                                <i class="fas fa-map-marker-alt"></i>Addresses
                            </a>
                        </li>
                        <li>
                            <a asp-area="UserPanel" asp-controller="Account" asp-action="Index">
                                <i class="fas fa-user"></i>Account
                                details
                            </a>
                        </li>
                        <li>
                            <a asp-area="UserPanel" asp-controller="BeVendor" asp-action="Index">
                                <i class="fas fa-cloud-download-alt"></i>Become A Vendor
                            </a>
                        </li>
                        <li><a asp-area="UserPanel" asp-controller="Dashboard" asp-action="LogOut">
                            <i class="fas fa-sign-out-alt"></i>logout
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-12 col-md-12 col-lg-9">
                <!-- Tab panes -->
                <div class="tab-content dashboard_content">
                    @RenderBody()                    
                </div>
            </div>
        </div>
    </div>
</section>

@RenderSection("Scriptss",false)